#!/usr/bin/env bash
# Installs and setup haproxy
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.7
apt-get install haproxy=2.7.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 89492-web-01 10.247.15.223:80 check
   server 89492-web-02 10.247.104.26:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
