#!/usr/bin/env bash
#Transfers files from client to server

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	echo "Host *" > ~/.ssh/config
	echo "  StrictHostKeyChecking no" >> ~/.ssh/config
	scp -i $4 $1 $3@$2:~/
	rm ~/.ssh/config
fi
