#!/usr/bin/env bash
#Print FizzBuzz when num is multiple of 3 and 5
#Print Fizz when num is multiple of 3
#Print Buzz whne num is mutiple of 5
for ((i = 1; i <= 100; i++))
do
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
