#!/usr/bin/env bash
#reads /etc/passwd and cuts part of it
fl="/etc/passwd"
while IFS=':' read -r col1 col2 col3 col4 col5 col6 col7
do
	i="$col1$col2$col4$col7"
	i=$i
	echo "$col5:$col3:$col6"
done <$fl
