#!/usr/bin/env bash
#Prints 'Best School' 10 times but on the 9th print 'Hi' after Best school
i=0
while [ $i -lt 10 ]
do
	echo "Best School"
	if [ $i -eq 8 ]
	then
		echo "Hi"
	fi
	i=$((i + 1))
done
