#!/usr/bin/env bash
#Change ip address of localhost and facebook.com to resolve to
# 127.0.0.2 and 8.8.8.8 repectively

echo "127.0.0.2    localhost">~/hosts.new
echo "8.8.8.8     facebook.com">>~/hosts.new
cp -f ~/hosts.new /etc/hosts
